import { ChakraProvider } from '@chakra-ui/react';
import theme from '../../theme';
import Head from 'next/head'
import Header from '@component/components/Header'
import { Flex, Box, Heading, Text} from '@chakra-ui/react';
import ContactButton from '@component/components/ContactButton';
import DownloadResumeButton from '@component/components/DownloadResumeButton';

export default function Home() {
  return (
    <ChakraProvider theme={theme}>
      <>
        <Head>
          <title>Alan Flores Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/assets/icons/logo.svg" />
        </Head>
        <Header/>
        <Flex position="relative">
          <Box h="496px" w="full" bg="gray.900" blendMode="overlay" opacity="30%">
            <Box h="496px" backgroundImage="/assets/images/hero-image.webp" backgroundSize="cover" filter="grayscale(100%)" opacity="100%">
            </Box>
          </Box>
          <Flex direction="column" alignItems="center" position="absolute" top="50%" left="50%" transform="translate(-50%, -50%)">
            <Heading as="h1" color="gray.50" fontSize="6xl" mb="24px">
              ¡Hola! Soy <Text as="span" color="mainColor">Alan Flores</Text>
            </Heading>
            <Heading as="h2" color="gray.400" fontSize="4xl" mb="64px">
              Desarrollador Frontend
            </Heading>
            <Flex>
              <ContactButton/>
              <DownloadResumeButton/>
            </Flex>
          </Flex>
        </Flex>
        <main> 
          
        </main>
      </>
    </ChakraProvider>
  )
}
