import { ChakraProvider } from '@chakra-ui/react';
import theme from '../../theme';
import { Container } from '@chakra-ui/react';
import Head from 'next/head'
import Header from '@component/components/sections/Header'
import Hero from '@component/components/sections/Hero';
import AboutMe from '@component/components/sections/AboutMe';
import Skills from '@component/components/sections/Skills';
import Projects from '@component/components/sections/Projects';
import Education from '@component/components/sections/Education';
import Contact from '@component/components/sections/Contact';
import Footer from '@component/components/sections/Footer';

export default function Home() {
  return (
    <ChakraProvider theme={theme}>
      <>
        <Head>
          <title>Alan Flores Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/assets/icons/logo.svg" />
        </Head>
        <Header/>
        <Hero/>
        <AboutMe/>
        <Skills/>
        <Projects/>
        <Education/>
        <Contact/>
        <Footer/>
      </>
    </ChakraProvider>
  )
}
